//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUSUProgramming.MusicDownloader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SUSUProgramming.MusicDownloader.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit path.
        /// </summary>
        public static string AddOrEditPath {
            get {
                return ResourceManager.GetString("AddOrEditPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add path.
        /// </summary>
        public static string AddPath {
            get {
                return ResourceManager.GetString("AddPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use online services, you should authorize an app. Would you like to?.
        /// </summary>
        public static string AuthConfirmation {
            get {
                return ResourceManager.GetString("AuthConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Failed :(.
        /// </summary>
        public static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autotag.
        /// </summary>
        public static string AutoTag {
            get {
                return ResourceManager.GetString("AutoTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto tag on download.
        /// </summary>
        public static string AutoTagOnDownload {
            get {
                return ResourceManager.GetString("AutoTagOnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically search metadata online in services such as Last.FM, Genius, LrcLib etc..
        /// </summary>
        public static string AutoTagTip {
            get {
                return ResourceManager.GetString("AutoTagTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete tags.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string ConfirmAuth {
            get {
                return ResourceManager.GetString("ConfirmAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict detected.
        /// </summary>
        public static string Conflicting {
            get {
                return ResourceManager.GetString("Conflicting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve conflicts detected when tagging.
        /// </summary>
        public static string ConflictsTip {
            get {
                return ResourceManager.GetString("ConflictsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve conflicts.
        /// </summary>
        public static string ConflictsWindow {
            get {
                return ResourceManager.GetString("ConflictsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2024 IOExcept10n. For contacts write via Telegram: t.me/ioexcept10n. This release is not for sale..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete cover.
        /// </summary>
        public static string DeleteCover {
            get {
                return ResourceManager.GetString("DeleteCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected tracks.
        /// </summary>
        public static string DeleteTip {
            get {
                return ResourceManager.GetString("DeleteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete track.
        /// </summary>
        public static string DeleteTrack {
            get {
                return ResourceManager.GetString("DeleteTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and play.
        /// </summary>
        public static string DownloadAndPlay {
            get {
                return ResourceManager.GetString("DownloadAndPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download track.
        /// </summary>
        public static string DownloadTip {
            get {
                return ResourceManager.GetString("DownloadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing fault.
        /// </summary>
        public static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found conflicts:.
        /// </summary>
        public static string FoundConflicts {
            get {
                return ResourceManager.GetString("FoundConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently listened.
        /// </summary>
        public static string FrequentlyListened {
            get {
                return ResourceManager.GetString("FrequentlyListened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project repo: https://github.com/IOExcept10n/MusicDownloader.
        /// </summary>
        public static string GithubReference {
            get {
                return ResourceManager.GetString("GithubReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string HandlingState {
            get {
                return ResourceManager.GetString("HandlingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags incomplete.
        /// </summary>
        public static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your query.
        /// </summary>
        public static string InputQuery {
            get {
                return ResourceManager.GetString("InputQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your value to resolve conflict.
        /// </summary>
        public static string InputValueHint {
            get {
                return ResourceManager.GetString("InputValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library tracks.
        /// </summary>
        public static string LibraryTracks {
            get {
                return ResourceManager.GetString("LibraryTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening state.
        /// </summary>
        public static string ListenState {
            get {
                return ResourceManager.GetString("ListenState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpopular.
        /// </summary>
        public static string LowListened {
            get {
                return ResourceManager.GetString("LowListened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage blacklisted paths.
        /// </summary>
        public static string ManageBlacklist {
            get {
                return ResourceManager.GetString("ManageBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage tracked paths.
        /// </summary>
        public static string ManageTracked {
            get {
                return ResourceManager.GetString("ManageTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark track as unsorted.
        /// </summary>
        public static string MarkAsUnsorted {
            get {
                return ResourceManager.GetString("MarkAsUnsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe tag issues.
        /// </summary>
        public static string MayBeIncorrect {
            get {
                return ResourceManager.GetString("MayBeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media library.
        /// </summary>
        public static string MediaLibrary {
            get {
                return ResourceManager.GetString("MediaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Preferences.
        /// </summary>
        public static string MetadataPreferences {
            get {
                return ResourceManager.GetString("MetadataPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move tracks into the selected path.
        /// </summary>
        public static string MoveTip {
            get {
                return ResourceManager.GetString("MoveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to....
        /// </summary>
        public static string MoveTrackTo {
            get {
                return ResourceManager.GetString("MoveTrackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My music.
        /// </summary>
        public static string MyMusic {
            get {
                return ResourceManager.GetString("MyMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online search.
        /// </summary>
        public static string OnlineSearch {
            get {
                return ResourceManager.GetString("OnlineSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online services.
        /// </summary>
        public static string OnlineServices {
            get {
                return ResourceManager.GetString("OnlineServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open local library.
        /// </summary>
        public static string OpenLibrary {
            get {
                return ResourceManager.GetString("OpenLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string PathDialog {
            get {
                return ResourceManager.GetString("PathDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist..
        /// </summary>
        public static string PathDoesNotExist {
            get {
                return ResourceManager.GetString("PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play track with default player.
        /// </summary>
        public static string PlayTrack {
            get {
                return ResourceManager.GetString("PlayTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging progress.
        /// </summary>
        public static string ProgressTip {
            get {
                return ResourceManager.GetString("ProgressTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh tracks view.
        /// </summary>
        public static string RefreshTip {
            get {
                return ResourceManager.GetString("RefreshTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject All.
        /// </summary>
        public static string RejectAll {
            get {
                return ResourceManager.GetString("RejectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string Res2FALabel {
            get {
                return ResourceManager.GetString("Res2FALabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string ResolveConflicts {
            get {
                return ResourceManager.GetString("ResolveConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search tracks online.
        /// </summary>
        public static string SearchOnline {
            get {
                return ResourceManager.GetString("SearchOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search tracks with given query.
        /// </summary>
        public static string SearchTip {
            get {
                return ResourceManager.GetString("SearchTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all tracks.
        /// </summary>
        public static string SelectAllTip {
            get {
                return ResourceManager.GetString("SelectAllTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path.
        /// </summary>
        public static string SelectPath {
            get {
                return ResourceManager.GetString("SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to move tracks to..
        /// </summary>
        public static string SelectPathTip {
            get {
                return ResourceManager.GetString("SelectPathTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set cover from clipboard.
        /// </summary>
        public static string SetFromClipboard {
            get {
                return ResourceManager.GetString("SetFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set cover from file….
        /// </summary>
        public static string SetFromFile {
            get {
                return ResourceManager.GetString("SetFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewrite metadata on auto tagging.
        /// </summary>
        public static string ShouldRewriteMetadata {
            get {
                return ResourceManager.GetString("ShouldRewriteMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show track in explorer.
        /// </summary>
        public static string ShowInExplorer {
            get {
                return ResourceManager.GetString("ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep without changes.
        /// </summary>
        public static string StayUnresolved {
            get {
                return ResourceManager.GetString("StayUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully filled.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore track name.
        /// </summary>
        public static string SwitchIgnore {
            get {
                return ResourceManager.GetString("SwitchIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsCount {
            get {
                return ResourceManager.GetString("TagsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags not found.
        /// </summary>
        public static string TagsNotFound {
            get {
                return ResourceManager.GetString("TagsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string TrackAlbum {
            get {
                return ResourceManager.GetString("TrackAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album artist.
        /// </summary>
        public static string TrackAlbumArtist {
            get {
                return ResourceManager.GetString("TrackAlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string TrackArtist {
            get {
                return ResourceManager.GetString("TrackArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string TrackComment {
            get {
                return ResourceManager.GetString("TrackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks count.
        /// </summary>
        public static string TrackCount {
            get {
                return ResourceManager.GetString("TrackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string TrackCover {
            get {
                return ResourceManager.GetString("TrackCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TrackDescription {
            get {
                return ResourceManager.GetString("TrackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string TrackDisc {
            get {
                return ResourceManager.GetString("TrackDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc count.
        /// </summary>
        public static string TrackDiscCount {
            get {
                return ResourceManager.GetString("TrackDiscCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string TrackGenres {
            get {
                return ResourceManager.GetString("TrackGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string TrackLyrics {
            get {
                return ResourceManager.GetString("TrackLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track position.
        /// </summary>
        public static string TrackNumber {
            get {
                return ResourceManager.GetString("TrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string TrackSubtitle {
            get {
                return ResourceManager.GetString("TrackSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TrackTitle {
            get {
                return ResourceManager.GetString("TrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string TrackYear {
            get {
                return ResourceManager.GetString("TrackYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsorted Tracks.
        /// </summary>
        public static string UnsortedLibraryTracks {
            get {
                return ResourceManager.GetString("UnsortedLibraryTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags.
        /// </summary>
        public static string Untagged {
            get {
                return ResourceManager.GetString("Untagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your VK ID credentials.
        /// </summary>
        public static string VKAuthorizationLabel {
            get {
                return ResourceManager.GetString("VKAuthorizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have conflicted tags:.
        /// </summary>
        public static string YouHaveConflictedTags {
            get {
                return ResourceManager.GetString("YouHaveConflictedTags", resourceCulture);
            }
        }
    }
}
